#pragma once

#include <glfw/glfw3.h>

#define DECLARE_TEST_FUNC(ns) namespace ns { void RenderScene(); }

DECLARE_TEST_FUNC(E17)
DECLARE_TEST_FUNC(E16)
DECLARE_TEST_FUNC(E15)
DECLARE_TEST_FUNC(E14)
DECLARE_TEST_FUNC(E13)
DECLARE_TEST_FUNC(E12)
DECLARE_TEST_FUNC(E11)
DECLARE_TEST_FUNC(E10)
DECLARE_TEST_FUNC(E9)
DECLARE_TEST_FUNC(E8)
DECLARE_TEST_FUNC(E7)
DECLARE_TEST_FUNC(E6)
DECLARE_TEST_FUNC(E5)
DECLARE_TEST_FUNC(E4)
DECLARE_TEST_FUNC(E3)
DECLARE_TEST_FUNC(E2)
DECLARE_TEST_FUNC(E1)

#define CALL_TEST_FUNC(ns) ns::RenderScene()

void TestRender();
void TestLogl();
void TestGLM();
